#!/usr/bin/env python
#-*- coding: utf-8 -*-

from vm import Vm
from optparse import OptionParser
import os

if __name__ == '__main__':

    parser = OptionParser('%s VM_name [snapshot_name]' % __file__)
    (options, args) = parser.parse_args()

    if len(args) == 1:
        Vm(args[0]).snap_restore()
    elif len(args) == 2:
        Vm(args[0]).snap_restore(args[1])
    else:
        os.execlp(__file__, __file__, '--help')
