#!/usr/bin/env python
#-*- coding: utf-8 -*-

from vm import Vm
from optparse import OptionParser
import os

if __name__ == '__main__':

    parser = OptionParser('%s VM_name snapshot_name.' % __file__)
    (options, args) = parser.parse_args()

    if not len(args) == 2:
        os.execlp(__file__, __file__, '--help')

    Vm(args[0]).snap_remove(args[1])
