#!/usr/bin/env python
# -*- coding: utf-8 -*-

from vm import Vm
import os
import re
import sys


def help():
    sys.stderr.write('Usage: %s [ssh options] [user_name@]vm_name '
                     ' [-- commands]\n' % __file__)
    sys.exit(1)


def parse_host(hostname):
    m = re.match('^(?P<user>.+)@(?P<vm>.+)$', hostname)
    if m:
        user = m.groupdict()['user']
        vm = Vm(m.groupdict()['vm'])
    else:
        user = None
        vm = Vm(hostname)

    try:
        port = [pf['host port'] for pf in vm.port_forward
                if pf['name'] == 'ssh'][0]
    except IndexError:
        sys.stderr.write('%s has no port forward settings named "ssn".'
                         % vm.name)
        sys.exit(1)

    if user:
        return ['-p', port,  '%s@localhost' % user]
    else:
        return ['-p', port, 'localhost']


if __name__ == '__main__':

    if len(sys.argv) < 2:
        help()

    cmd = ['ssh']
    iter_args = iter(sys.argv[1:])

    # Parse ssh options
    for i in iter_args:
        if i == '--':
            break
        else:
            cmd.append(i)

    # Parse VM name and change it to port and localhost.
    cmd.extend(parse_host(cmd.pop()))

    # Parse ssh commands
    for i in iter_args:
        cmd.append(i)

    os.execvp('ssh', cmd)
