#!/usr/bin/env python
#-*- coding: utf-8 -*-

from vm import Vm
import random
import errno
import socket
from optparse import OptionParser
import os


def is_available_port(port):
    s = None
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.bind(('127.0.0.1', port))

        return True
    except OSError as e:
        if e.errno == errno.EADDRINUSE:
            return False
    finally:
        if s:
            s.close()

def up(vm, gui=False):

    if vm.ssh_port and is_available_port(vm.ssh_port):
        pass
    else:
        host_port = random.randrange(49153, 65536)
        while not is_available_port(host_port):
            host_port = random.randrange(49153, 65536)
        vm.set_ssh_port(host_port)

    vm.up()


if __name__ == '__main__':

    parser = OptionParser('%s [-g] VM1 [VM2 ...]' % __file__)
    parser.add_option('-g', '--gui', dest='gui', action='store_true',
                      default=False,
                      help='Make GUI available.')
    options, vms = parser.parse_args()

    if not vms:
        os.execlp(__file__, __file__, '--help')

    
    [up(Vm(vm), options.gui) for vm in vms]
