#!/usr/bin/env python
#-*- coding: utf-8 -*-

from vm import Vm
import sys
import random
import errno
import socket
from optparse import OptionParser
import os

def is_available_port(port):
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(('127.0.0.1', port))

        return True
    except OSError as e:
        if e.errno == errno.EADDRINUSE:
            return False


def up(name):
    vm = Vm(name)

    if is_available_port(vm.ssh_port):
        pass
    else:
        host_port = random.randrange(49153, 65536)
        while not is_available_port(host_port):
            host_port = random.randrange(49153, 65536)
        vm.set_ssh_port(host_port)

    vm.up()
    sys.stdout.write('%s is starting.\n' % name)

if __name__ == '__main__':

    for vm in sys.argv[1:]:
        up(vm)
